In [2]:
import pandas as pd

caminho_arquivo = "Dados Tratados .xlsx" 
df = pd.read_excel(caminho_arquivo)

# Ação aplicada na tabela (df) e não na biblioteca (pd)
df.head()

    Estado   Taxa de MVI  Renda  Gini   Desmprego Médio 2024
0      Acre    20.326334   1271  0.502                 7.700
1   Alagoas    35.433638   1331  0.516                 8.500
2     Amapá    45.090099   1514  0.509                 9.200
3  Amazonas    27.398803   1238  0.474                 8.575
4     Bahia    40.645061   1366  0.477                11.175

In [3]:
from sklearn.preprocessing import MinMaxScaler

normalizador = MinMaxScaler()
colunas_alvo = ['Taxa de MVI','Renda','Gini ', 'Desmprego Médio 2024']

df[colunas_alvo] = normalizador.fit_transform(df[colunas_alvo])

df.head()

    Estado   Taxa de MVI     Renda     Gini   Desmprego Médio 2024
0      Acre     0.329459  0.081960  0.615385              0.574018
1   Alagoas     0.738527  0.107309  0.735043              0.670695
2     Amapá     1.000000  0.184622  0.675214              0.755287
3  Amazonas     0.520963  0.068019  0.376068              0.679758
4     Bahia     0.879639  0.122095  0.401709              0.993958

In [6]:
from sklearn.cluster import KMeans

agrupador = KMeans(n_clusters=3,random_state=42)

df['Cluster Matemático']=agrupador.fit_predict(df[colunas_alvo])

df.head()

    Estado   Taxa de MVI  ...  Desmprego Médio 2024  Cluster Matemático
0      Acre     0.329459  ...              0.574018                   1
1   Alagoas     0.738527  ...              0.670695                   2
2     Amapá     1.000000  ...              0.755287                   2
3  Amazonas     0.520963  ...              0.679758                   2
4     Bahia     0.879639  ...              0.993958                   2

[5 rows x 6 columns]

In [7]:
df.groupby('Cluster Matemático')[colunas_alvo].mean()

                    Taxa de MVI     Renda     Gini   Desmprego Médio 2024
Cluster Matemático
0                      0.276578  0.484503  0.251748              0.184839
1                      0.309667  0.340576  0.737485              0.671558
2                      0.705122  0.105901  0.566002              0.715341

In [9]:
dicionario_clustr = {
0:'Vulneravel',
1:'Intermediario',
2:'Desenvolvido'
}

df['Perfil Socioeconomico'] = df['Cluster Matemático'].map(dicionario_clustr)

df.head()

    Estado   Taxa de MVI  ...  Cluster Matemático  Perfil Socioeconomico
0      Acre     0.329459  ...                   1          Intermediario
1   Alagoas     0.738527  ...                   2           Desenvolvido
2     Amapá     1.000000  ...                   2           Desenvolvido
3  Amazonas     0.520963  ...                   2           Desenvolvido
4     Bahia     0.879639  ...                   2           Desenvolvido

[5 rows x 7 columns]

In [10]:
matriz_correlacao = df[colunas_alvo].corr(method='pearson')

matriz_correlacao

                      Taxa de MVI     Renda     Gini   Desmprego Médio 2024
Taxa de MVI              1.000000 -0.688277  0.186983              0.454806
Renda                   -0.688277  1.000000 -0.130724             -0.394881
Gini                     0.186983 -0.130724  1.000000              0.776640
Desmprego Médio 2024     0.454806 -0.394881  0.776640              1.000000

In [11]:
nome_arquivo_final = "base_mvi_precessada.xlsx"
df.to_excel(nome_arquivo_final,index=False)
print('Base de dados importada!')

Base de dados importada!

In [13]:
import sqlite3

conexão =sqlite3.connect("banco_seguranca_publica.db")

df.to_sql('tb_indicadores_estaduais',conexão,if_exists="replace",index=False)

conexão.close()

print("Dados Enviados ao bando de dados!")

Dados Enviados ao bando de dados!